# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayitol.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_kayitoll(object):
    def setupUi(self, kayitoll):
        kayitoll.setObjectName("kayitoll")
        kayitoll.resize(415, 489)
        kayitoll.setMinimumSize(QtCore.QSize(415, 489))
        kayitoll.setMaximumSize(QtCore.QSize(415, 489))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Sulu-boya-kitap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        kayitoll.setWindowIcon(icon)
        kayitoll.setStyleSheet("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"Spacer\" name=\"horizontalSpacer_3\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>91</x>\n"
"     <y>1</y>\n"
"     <width>41</width>\n"
"     <height>42</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"font\">\n"
"    <font>\n"
"     <family>MS Sans Serif</family>\n"
"     <pointsize>10</pointsize>\n"
"    </font>\n"
"   </property>\n"
"   <property name=\"orientation\">\n"
"    <enum>Qt::Horizontal</enum>\n"
"   </property>\n"
"   <property name=\"sizeHint\" stdset=\"0\">\n"
"    <size>\n"
"     <width>40</width>\n"
"     <height>20</height>\n"
"    </size>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"")
        self.centralwidget = QtWidgets.QWidget(kayitoll)
        self.centralwidget.setObjectName("centralwidget")
        self.kayitol = QtWidgets.QPushButton(self.centralwidget)
        self.kayitol.setGeometry(QtCore.QRect(220, 400, 161, 21))
        self.kayitol.setStyleSheet("/* author = Nathan Woodrow */\n"
"\n"
"QToolTip\n"
"{\n"
"    border: 1px solid #222;\n"
"    background-color: #333;\n"
"    color: #aaa;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #aaa;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: #507098;\n"
"    color: #aaa;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: #507098;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    /*\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"    */\n"
"    background: #444;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    border: 1px solid #000;\n"
"    background-color: #444;\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* MENU                                                                                 */\n"
"/* ==================================================================================== */\n"
"\n"
"QMenu\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #222;\n"
"    padding: 4px;\n"
"    padding-right: 0px;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    background: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #507098;\n"
"    color: #aaa;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #404040;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    padding: 1px;\n"
"    border: 1px solid #111;\n"
"    background-color: #888;\n"
"    color: #111;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"/*    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);*/\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"/*    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);*/\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* COMBO BOX                                                                            */\n"
"/* ==================================================================================== */\n"
"\n"
"QComboBox {\n"
"    selection-background-color: #ffaa00;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0     #565656,\n"
"        stop: 0.1   #525252,\n"
"        stop: 0.5   #4e4e4e,\n"
"        stop: 0.9   #4a4a4a,\n"
"        stop: 1     #464646);\n"
"}\n"
"\n"
"\n"
"QComboBox:on {\n"
"    padding-top: 1px;\n"
"    padding-left: 3px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0     #555,\n"
"        stop: 0.1   #4C4C4C,\n"
"        stop: 0.5   #464646,\n"
"        stop: 0.9   #414141,\n"
"        stop: 1     #444);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #222;\n"
"    selection-background-color: #507098;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"     border: 0px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    image: url(icons/down_arrow.png);\n"
"}\n"
"QLineEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* SCROLL BAR                                                                           */\n"
"/* ==================================================================================== */\n"
"\n"
"QScrollBar:horizontal {\n"
"    background-color: #333;\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    border: 1px solid #111;\n"
"    background: #535353;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    width: 0px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: #333;\n"
"    width: 8px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    border: 1px solid #111;\n"
"    background: #535353;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    height: 0px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QSizeGrip\n"
"{\n"
"  width: 1px;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    /*background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);*/\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"QDockWidget\n"
"{\n"
"      titlebar-close-icon: url(icons/cross.svg);\n"
"}\n"
"\n"
"QDockWidget::separator\n"
"{\n"
"    border: 1px solid red;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: #323232;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    /*background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);*/\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 0px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    /*background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);*/\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar {\n"
"    background: #323232;\n"
"    border: 1px solid #323232;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal\n"
"{\n"
"    image: url(:/qss_icons/rc/Hmovetoolbar.png);\n"
"}\n"
"\n"
"QToolBar::handle:vertical\n"
"{\n"
"    image: url(:/qss_icons/rc/Vmovetoolbar.png);\n"
"}\n"
"\n"
"QToolBar::separator:horizontal\n"
"{\n"
"    image: url(:/qss_icons/rc/Hsepartoolbar.png);\n"
"}\n"
"\n"
"QToolBar::separator:vertical\n"
"{\n"
"    image: url(:/qss_icons/rc/Vsepartoolbars.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    /*\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    */\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
"  margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    /*background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);*/\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    /*background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);*/\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* RADIO BUTTON                                                                         */\n"
"/* ==================================================================================== */\n"
"\n"
"QGroupBox::indicator:unchecked,\n"
"QGroupBox::indicator:checked,\n"
"QCheckBox::indicator:checked,\n"
"QCheckBox::indicator:unchecked,\n"
"QRadioButton::indicator:checked,\n"
"QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"}\n"
"\n"
"QGroupBox::indicator:checked,\n"
"QCheckBox::indicator:checked,\n"
"QRadioButton::indicator:checked {\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"}\n"
"\n"
"QGroupBox::indicator:hover,\n"
"QCheckBox::indicator:hover,\n"
"QRadioButton::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* CHECKBOX                                                                             */\n"
"/* ==================================================================================== */\n"
"\n"
"QAbstractItemView\n"
"{\n"
"  background-color: #222;\n"
"    alternate-background-color: #323232;\n"
"    color: silver;\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    padding: 1px;\n"
"}\n"
"\n"
"QAbstractItemView::selected {\n"
"    border: 0px;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* TREE VIEW                                                                            */\n"
"/* ==================================================================================== */\n"
"\n"
"QTreeView {\n"
"    border: 0.5px solid rgba(108,108,108,75);\n"
"}\n"
"\n"
"QTreeView::item, QTreeView::branch {\n"
"    background: transparent;\n"
"    color: #DDD;\n"
"}\n"
"\n"
"QTreeView::item:hover, QTreeView::branch:hover {\n"
"    background-color: #507098;\n"
"    color: #DDD;\n"
"}\n"
"\n"
"QTreeView::item:selected, QTreeView::branch:selected {\n"
"    background-color: #507098;\n"
"    color: #DDD;\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"    border-image: none;\n"
"    image: url(icons/caret-right_ffffff_14.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings {\n"
"     border-image: none;\n"
"     image: url(icons/caret-down_ffffff_14.png);\n"
"}\n"
"\n"
"QgsLayerTreeView\n"
"{\n"
"}\n"
"\n"
"QgsLayerTreeView::item\n"
"{\n"
"    border-top: 0.5px solid rgba(108,108,108,50);\n"
"    border-bottom: 0.5px solid rgba(108,108,108,50);\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QgsLayerTreeView::indicator:unchecked{\n"
"    image: url(icons/eye-blocked.svg);\n"
"}\n"
"\n"
"QgsLayerTreeView::indicator:checked {\n"
"    image: url(icons/eye.svg);\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* TABLE VIEW                                                                           */\n"
"/* ==================================================================================== */\n"
"\n"
"QHeaderView {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: transparent;\n"
"    background-color: #323232;\n"
"    color: #777;\n"
"    border-right: 0px solid #777;\n"
"    border-top: 0px solid #777;\n"
"    padding: 0 0 2px 3px\n"
"}")
        self.kayitol.setObjectName("kayitol")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 381, 361))
        self.groupBox.setObjectName("groupBox")
        self.frameKayit = QtWidgets.QFrame(self.groupBox)
        self.frameKayit.setGeometry(QtCore.QRect(10, 20, 341, 331))
        self.frameKayit.setStyleSheet("border-radius:30px;")
        self.frameKayit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameKayit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameKayit.setObjectName("frameKayit")
        self.lineEditSifre = QtWidgets.QLineEdit(self.frameKayit)
        self.lineEditSifre.setGeometry(QtCore.QRect(30, 120, 301, 41))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.lineEditSifre.setFont(font)
        self.lineEditSifre.setText("")
        self.lineEditSifre.setFrame(True)
        self.lineEditSifre.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEditSifre.setClearButtonEnabled(True)
        self.lineEditSifre.setObjectName("lineEditSifre")
        self.lineEditSifreTekrar = QtWidgets.QLineEdit(self.frameKayit)
        self.lineEditSifreTekrar.setGeometry(QtCore.QRect(30, 170, 301, 41))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.lineEditSifreTekrar.setFont(font)
        self.lineEditSifreTekrar.setText("")
        self.lineEditSifreTekrar.setFrame(True)
        self.lineEditSifreTekrar.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEditSifreTekrar.setClearButtonEnabled(True)
        self.lineEditSifreTekrar.setObjectName("lineEditSifreTekrar")
        self.lineEditEmail = QtWidgets.QLineEdit(self.frameKayit)
        self.lineEditEmail.setGeometry(QtCore.QRect(30, 270, 301, 41))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setText("")
        self.lineEditEmail.setFrame(True)
        self.lineEditEmail.setClearButtonEnabled(True)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditTel = QtWidgets.QLineEdit(self.frameKayit)
        self.lineEditTel.setGeometry(QtCore.QRect(90, 220, 241, 41))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.lineEditTel.setFont(font)
        self.lineEditTel.setMaxLength(15)
        self.lineEditTel.setFrame(True)
        self.lineEditTel.setCursorPosition(15)
        self.lineEditTel.setDragEnabled(False)
        self.lineEditTel.setPlaceholderText("")
        self.lineEditTel.setClearButtonEnabled(True)
        self.lineEditTel.setObjectName("lineEditTel")
        self.labelTel = QtWidgets.QLabel(self.frameKayit)
        self.labelTel.setGeometry(QtCore.QRect(30, 216, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Elephant")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTel.setFont(font)
        self.labelTel.setObjectName("labelTel")
        self.lineEditKulAdi = QtWidgets.QLineEdit(self.frameKayit)
        self.lineEditKulAdi.setGeometry(QtCore.QRect(30, 70, 301, 41))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.lineEditKulAdi.setFont(font)
        self.lineEditKulAdi.setText("")
        self.lineEditKulAdi.setFrame(True)
        self.lineEditKulAdi.setClearButtonEnabled(True)
        self.lineEditKulAdi.setObjectName("lineEditKulAdi")
        self.lineEditAdSoyad = QtWidgets.QLineEdit(self.frameKayit)
        self.lineEditAdSoyad.setGeometry(QtCore.QRect(30, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.lineEditAdSoyad.setFont(font)
        self.lineEditAdSoyad.setInputMask("")
        self.lineEditAdSoyad.setText("")
        self.lineEditAdSoyad.setFrame(True)
        self.lineEditAdSoyad.setClearButtonEnabled(True)
        self.lineEditAdSoyad.setObjectName("lineEditAdSoyad")
        self.giris = QtWidgets.QPushButton(self.centralwidget)
        self.giris.setGeometry(QtCore.QRect(40, 400, 161, 21))
        self.giris.setStyleSheet("/* author = Nathan Woodrow */\n"
"\n"
"QToolTip\n"
"{\n"
"    border: 1px solid #222;\n"
"    background-color: #333;\n"
"    color: #aaa;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #aaa;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: #507098;\n"
"    color: #aaa;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: #507098;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    /*\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"    */\n"
"    background: #444;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    border: 1px solid #000;\n"
"    background-color: #444;\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* MENU                                                                                 */\n"
"/* ==================================================================================== */\n"
"\n"
"QMenu\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #222;\n"
"    padding: 4px;\n"
"    padding-right: 0px;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    background: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #507098;\n"
"    color: #aaa;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #404040;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    padding: 1px;\n"
"    border: 1px solid #111;\n"
"    background-color: #888;\n"
"    color: #111;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"/*    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);*/\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"/*    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);*/\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* COMBO BOX                                                                            */\n"
"/* ==================================================================================== */\n"
"\n"
"QComboBox {\n"
"    selection-background-color: #ffaa00;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0     #565656,\n"
"        stop: 0.1   #525252,\n"
"        stop: 0.5   #4e4e4e,\n"
"        stop: 0.9   #4a4a4a,\n"
"        stop: 1     #464646);\n"
"}\n"
"\n"
"\n"
"QComboBox:on {\n"
"    padding-top: 1px;\n"
"    padding-left: 3px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0     #555,\n"
"        stop: 0.1   #4C4C4C,\n"
"        stop: 0.5   #464646,\n"
"        stop: 0.9   #414141,\n"
"        stop: 1     #444);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #222;\n"
"    selection-background-color: #507098;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"     border: 0px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    image: url(icons/down_arrow.png);\n"
"}\n"
"QLineEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* SCROLL BAR                                                                           */\n"
"/* ==================================================================================== */\n"
"\n"
"QScrollBar:horizontal {\n"
"    background-color: #333;\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    border: 1px solid #111;\n"
"    background: #535353;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    width: 0px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: #333;\n"
"    width: 8px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    border: 1px solid #111;\n"
"    background: #535353;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    height: 0px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QSizeGrip\n"
"{\n"
"  width: 1px;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    /*background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);*/\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"QDockWidget\n"
"{\n"
"      titlebar-close-icon: url(icons/cross.svg);\n"
"}\n"
"\n"
"QDockWidget::separator\n"
"{\n"
"    border: 1px solid red;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: #323232;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    /*background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);*/\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 0px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    /*background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);*/\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar {\n"
"    background: #323232;\n"
"    border: 1px solid #323232;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal\n"
"{\n"
"    image: url(:/qss_icons/rc/Hmovetoolbar.png);\n"
"}\n"
"\n"
"QToolBar::handle:vertical\n"
"{\n"
"    image: url(:/qss_icons/rc/Vmovetoolbar.png);\n"
"}\n"
"\n"
"QToolBar::separator:horizontal\n"
"{\n"
"    image: url(:/qss_icons/rc/Hsepartoolbar.png);\n"
"}\n"
"\n"
"QToolBar::separator:vertical\n"
"{\n"
"    image: url(:/qss_icons/rc/Vsepartoolbars.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    /*\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    */\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
"  margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    /*background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);*/\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    /*background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);*/\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* RADIO BUTTON                                                                         */\n"
"/* ==================================================================================== */\n"
"\n"
"QGroupBox::indicator:unchecked,\n"
"QGroupBox::indicator:checked,\n"
"QCheckBox::indicator:checked,\n"
"QCheckBox::indicator:unchecked,\n"
"QRadioButton::indicator:checked,\n"
"QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"}\n"
"\n"
"QGroupBox::indicator:checked,\n"
"QCheckBox::indicator:checked,\n"
"QRadioButton::indicator:checked {\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"}\n"
"\n"
"QGroupBox::indicator:hover,\n"
"QCheckBox::indicator:hover,\n"
"QRadioButton::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* CHECKBOX                                                                             */\n"
"/* ==================================================================================== */\n"
"\n"
"QAbstractItemView\n"
"{\n"
"  background-color: #222;\n"
"    alternate-background-color: #323232;\n"
"    color: silver;\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    padding: 1px;\n"
"}\n"
"\n"
"QAbstractItemView::selected {\n"
"    border: 0px;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* TREE VIEW                                                                            */\n"
"/* ==================================================================================== */\n"
"\n"
"QTreeView {\n"
"    border: 0.5px solid rgba(108,108,108,75);\n"
"}\n"
"\n"
"QTreeView::item, QTreeView::branch {\n"
"    background: transparent;\n"
"    color: #DDD;\n"
"}\n"
"\n"
"QTreeView::item:hover, QTreeView::branch:hover {\n"
"    background-color: #507098;\n"
"    color: #DDD;\n"
"}\n"
"\n"
"QTreeView::item:selected, QTreeView::branch:selected {\n"
"    background-color: #507098;\n"
"    color: #DDD;\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"    border-image: none;\n"
"    image: url(icons/caret-right_ffffff_14.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings {\n"
"     border-image: none;\n"
"     image: url(icons/caret-down_ffffff_14.png);\n"
"}\n"
"\n"
"QgsLayerTreeView\n"
"{\n"
"}\n"
"\n"
"QgsLayerTreeView::item\n"
"{\n"
"    border-top: 0.5px solid rgba(108,108,108,50);\n"
"    border-bottom: 0.5px solid rgba(108,108,108,50);\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QgsLayerTreeView::indicator:unchecked{\n"
"    image: url(icons/eye-blocked.svg);\n"
"}\n"
"\n"
"QgsLayerTreeView::indicator:checked {\n"
"    image: url(icons/eye.svg);\n"
"}\n"
"\n"
"/* ==================================================================================== */\n"
"/* TABLE VIEW                                                                           */\n"
"/* ==================================================================================== */\n"
"\n"
"QHeaderView {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: transparent;\n"
"    background-color: #323232;\n"
"    color: #777;\n"
"    border-right: 0px solid #777;\n"
"    border-top: 0px solid #777;\n"
"    padding: 0 0 2px 3px\n"
"}")
        self.giris.setObjectName("giris")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        kayitoll.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(kayitoll)
        self.statusbar.setObjectName("statusbar")
        kayitoll.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(kayitoll)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 415, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuProgram = QtWidgets.QMenu(self.menuBar)
        self.menuProgram.setObjectName("menuProgram")
        kayitoll.setMenuBar(self.menuBar)
        self.actionKay_t_Ol = QtWidgets.QAction(kayitoll)
        self.actionKay_t_Ol.setObjectName("actionKay_t_Ol")
        self.actionGiri = QtWidgets.QAction(kayitoll)
        self.actionGiri.setObjectName("actionGiri")
        self.actionHakk_nda = QtWidgets.QAction(kayitoll)
        self.actionHakk_nda.setObjectName("actionHakk_nda")
        self.actionGiri_2 = QtWidgets.QAction(kayitoll)
        self.actionGiri_2.setObjectName("actionGiri_2")
        self.actionKay_t_Ol_2 = QtWidgets.QAction(kayitoll)
        self.actionKay_t_Ol_2.setObjectName("actionKay_t_Ol_2")
        self.actionHakk_nda_2 = QtWidgets.QAction(kayitoll)
        self.actionHakk_nda_2.setObjectName("actionHakk_nda_2")
        self.action_cikisk = QtWidgets.QAction(kayitoll)
        self.action_cikisk.setObjectName("action_cikisk")
        self.menuProgram.addAction(self.actionGiri_2)
        self.menuProgram.addAction(self.actionHakk_nda_2)
        self.menuProgram.addAction(self.action_cikisk)
        self.menuBar.addAction(self.menuProgram.menuAction())

        self.retranslateUi(kayitoll)
        QtCore.QMetaObject.connectSlotsByName(kayitoll)
        kayitoll.setTabOrder(self.lineEditAdSoyad, self.lineEditKulAdi)
        kayitoll.setTabOrder(self.lineEditKulAdi, self.lineEditSifre)
        kayitoll.setTabOrder(self.lineEditSifre, self.lineEditSifreTekrar)
        kayitoll.setTabOrder(self.lineEditSifreTekrar, self.lineEditTel)
        kayitoll.setTabOrder(self.lineEditTel, self.lineEditEmail)
        kayitoll.setTabOrder(self.lineEditEmail, self.kayitol)
        kayitoll.setTabOrder(self.kayitol, self.giris)

    def retranslateUi(self, kayitoll):
        _translate = QtCore.QCoreApplication.translate
        kayitoll.setWindowTitle(_translate("kayitoll", "Kütüphane - Kayıt Ol"))
        self.kayitol.setText(_translate("kayitoll", "Kayıt Ol"))
        self.groupBox.setTitle(_translate("kayitoll", "Kayıt Ol"))
        self.lineEditSifre.setToolTip(_translate("kayitoll", "<html><head/><body><p><span style=\" font-weight:600; color:#000000;\">Güvenliğiniz için şifrenizde </span><span style=\" font-weight:600; text-decoration: underline; color:#000000;\">büyük,küçük harf ve karakter</span><span style=\" font-weight:600; color:#000000;\"> kullanınız.</span></p></body></html>"))
        self.lineEditSifre.setPlaceholderText(_translate("kayitoll", "Şifre*"))
        self.lineEditSifreTekrar.setToolTip(_translate("kayitoll", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">Güvenliğiniz için şifrenizde </span><span style=\" font-size:9pt; font-weight:600; text-decoration: underline; color:#000000;\">büyük,küçük harf ve karakter</span><span style=\" font-size:9pt; font-weight:600; color:#000000;\"> kullanınız.</span></p></body></html>"))
        self.lineEditSifreTekrar.setPlaceholderText(_translate("kayitoll", "Şifre Tekrarı*"))
        self.lineEditEmail.setToolTip(_translate("kayitoll", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#000000;\">E-mail giriniz</span></p></body></html>"))
        self.lineEditEmail.setPlaceholderText(_translate("kayitoll", "E-Mail"))
        self.lineEditTel.setToolTip(_translate("kayitoll", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#000000;\">Telefon numaranızı giriniz</span></p></body></html>"))
        self.lineEditTel.setInputMask(_translate("kayitoll", "(599) 999 99 99"))
        self.lineEditTel.setText(_translate("kayitoll", "(5)   "))
        self.labelTel.setText(_translate("kayitoll", "TEL :"))
        self.lineEditKulAdi.setToolTip(_translate("kayitoll", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#000000;\">Kullanıcı Adı belirleyiniz</span></p></body></html>"))
        self.lineEditKulAdi.setPlaceholderText(_translate("kayitoll", "Kullanıcı Adı*"))
        self.lineEditAdSoyad.setToolTip(_translate("kayitoll", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#000000;\">Adınızı ve soyadınızı aralarında boşluk bırakarak giriniz</span></p></body></html>"))
        self.lineEditAdSoyad.setPlaceholderText(_translate("kayitoll", "Ad - Soyad*"))
        self.giris.setText(_translate("kayitoll", "Zaten Üyeyim"))
        self.menuProgram.setTitle(_translate("kayitoll", "Program"))
        self.actionKay_t_Ol.setText(_translate("kayitoll", "Kayıt Ol"))
        self.actionGiri.setText(_translate("kayitoll", "Giriş"))
        self.actionHakk_nda.setText(_translate("kayitoll", "Hakkında"))
        self.actionGiri_2.setText(_translate("kayitoll", "Giriş"))
        self.actionKay_t_Ol_2.setText(_translate("kayitoll", "Kayıt Ol"))
        self.actionHakk_nda_2.setText(_translate("kayitoll", "Hakkında"))
        self.action_cikisk.setText(_translate("kayitoll", "Çıkış"))

